version: 1.0.{build}
image: Visual Studio 2013
clone_depth: 50
environment:
  BUILD_ENV: MSVC
  PATH: C:\projects\cbmc\deps\bin;%PATH%
  INCLUDE: C:\projects\cbmc\deps\include
install:
- ps: |
    #check if dependencies were copied from cache, if not, download them.
    if (!(Test-Path deps)) {
    md deps
    }
    cd deps
    appveyor DownloadFile "https://storage.googleapis.com/diffblue-mirror/appveyor-deps/win_flex_bison-latest.zip?GoogleAccessId=diffbluemaster@diffblue-cr.iam.gserviceaccount.com&Expires=1543674503&Signature=CojdaOYrFl50gbxCQL%2BlfVtuo7j9v1OzfWD6jYIkfv1h7xzCacigAM51%2BVjaVx%2B8yvUjk%2B4MOU%2FKmLzev7dABWNi5n7p7SvlXYPFVVwDE57Me35Xi7BzW%2FhoSaPnVIGuhAmDfxjGoHhB0Of%2Fd2FfMl4cklGgc2YafTpFX3agNCE4dcc1UyG0SY5CbvTGTuBP%2B99zaQ69lNT1TSNUNp0PW2Hhj%2FPylts0IdDm713RA4wcNIHvLTTppBiNwMm0y%2B0qRG1op3R4vc5gahz%2B6dTUnCevYWO5l%2FIvmXQyo4XNkgqLKIRgk4wisLjtSuRh5vPyD%2FQPOrn2ubT53YnDcW6geA%3D%3D"
    7z x win_flex_bison-latest.zip -y
    Move-Item win_bison.exe bin\bison.exe -force
    Move-Item win_flex.exe bin\flex.exe -force
    Move-Item FlexLexer.h include\FlexLexer.h -force
    Move-Item data bin\data -force
    bison -V
    flex -V
    if (!(Test-Path bin\iconv.exe)) {
    & appveyor DownloadFile "https://storage.googleapis.com/diffblue-mirror/appveyor-deps/libiconv-1.9.2-1-bin.zip?GoogleAccessId=diffbluemaster@diffblue-cr.iam.gserviceaccount.com&Expires=1519839050&Signature=sS3Y2lC1oWOhBDsL8C9ASuO4LOM%2BpB%2F8PwG5w5CdB9JnPfLqhb3FnA1zkkZJoSNuIYS3DM6CN2qxoWjpJbLEtVQe0PpxziQZjLpJw2MpxXdJiJHRDu8x9THgzwuZ3ze5BWHzPoCBQPdRkKzVPezf1HwptUsm3Y9c2jlWljQjhc8NVsI4iPmjEOwT8E%2BYpR5fsLs2GsRjuoyqKa%2Bi4JJ6MbpXVX1IgR4fzp1Li9SnE39ujHDb%2FyI3c96eCdVm1Oa6jNxzSJNfq%2FgOZM8BIxlR55a%2BtM3oBQhU0voEtDOABwuO7ZBay8dLt%2FG5vz1%2Bi%2FIlRLFxQfICaprPLzw6pXRm8Q%3D%3D"
    & 7z x libiconv-1.9.2-1-bin.zip
    }
    if (!(Test-Path bin\libintl3.dll)) {
    & appveyor DownloadFile "https://storage.googleapis.com/diffblue-mirror/appveyor-deps/libintl-0.14.4-bin.zip?GoogleAccessId=diffbluemaster@diffblue-cr.iam.gserviceaccount.com&Expires=1519839050&Signature=lJViGr6bl%2F4i%2B6nIfeYChreq%2FKfgid9QqGSq7Ie%2FMG%2Fmr9nPyPUA%2BLtT7jn1ogunTzQLZP%2FNxVFcYqyd8gyuT%2Bn2MF80Ds4Whw4cRYnXPb2LZg4%2FiEqZV6wgBMIQfq5v2l3lAsglISVErOik%2BQAHec5gZe2%2BKaVjRnJnhPRziZkQyzF9Xdf2xsPi28hBaX4RQx8XqSLcY1kQpY13PDBZDi9lmdKHf0pBKu%2F0WXspmRAU02HtleMk6Zeg5vEDFcwoe8C3fb4vwtpwGwN9TX5ddaq56yUVn70zh%2BH2KgKIsRl26avnrCpeWF9M5lLck0ngaqFX84w%2BgxmZu40IVU%2Ff0A%3D%3D"
    & 7z x libintl-0.14.4-bin.zip
    }
    if (!(Test-Path bin\make.exe)) {
    & appveyor DownloadFile "https://storage.googleapis.com/diffblue-mirror/appveyor-deps/make-3.81-bin.zip?GoogleAccessId=diffbluemaster@diffblue-cr.iam.gserviceaccount.com&Expires=1519839050&Signature=PRC97AWzJ2ZAyjEK4p7eCbA3RAEr8sTf8TUK5zoMBcrXPUHWYjnCwXRMnIxUUufBYjsAx8t1XnOQdlTuAPJYpcha%2FFJRlcxMmfQjNbpNEQFJuqEpA5c%2FGhFYxSD3a26vjpgReUW5MuQXeLeNh7PziLB0GP0sdRHN%2B1eDiHeCJWYNMYhrEY9BAkf5rXeRQWr1ZG0Hzq%2FxZEHceypx8xyaT%2BFzREYQOyKjGdre1QXtI%2FXo4ImA1xWt%2F8TnlGcAnCEaTltxuSRVB%2F7s1ShMr9KoagCb%2BjBWq6BgbcNGxyzyOZfi2Sjjo39mhudF9DNbKbkczes9Kp3ySgXmrXSWjIG4Iw%3D%3D"
    & 7z x make-3.81-bin.zip
    }
    if (!(Test-Path bin\regex2.dll)) {
    & appveyor DownloadFile "https://storage.googleapis.com/diffblue-mirror/appveyor-deps/regex-2.7-bin.zip?GoogleAccessId=diffbluemaster@diffblue-cr.iam.gserviceaccount.com&Expires=1519839050&Signature=bXRvFV%2Be4Dpm8vzp%2F1bJWwgkERE6WakcPTBN57n9vNh0dr42jDTXv8JF%2BWCmTIb%2Fy4XzxYl0faggt3g6TqTLYn5UDVUBYx%2FMLmNVVNEv%2BaBlDd87UAZGLi6fkEV5oAP4W4FYsqEnKRDfGPOBoL7D7CuW9Kcxy3Moubxdl%2Bmes%2BMI%2FzWJ6BgLD3Oj04GyD42zLCYVtAzkeDAX0UADoh06ExhpTjI4BNnQ%2FhzSlPtPG7mon4q81%2F2tDNskKVJS466eR%2F8XV6H4QT3LoCkh6dxQ9%2B9ZnkWJplundRbiIlpj43vmdvjIChczl4jbAgL6zFj5Gz6u58uvCV%2FbOuyx3Sw1fg%3D%3D"
    & 7z x regex-2.7-bin.zip
    }
    if (!(Test-Path minisat2-2.2.1)) {
     & appveyor DownloadFile http://ftp.debian.org/debian/pool/main/m/minisat2/minisat2_2.2.1.orig.tar.gz
     & 7z x minisat2_2.2.1.orig.tar.gz
     &7z x minisat2_2.2.1.orig.tar
    }
    cd ..

cache: deps

build_script:
- cmd: |
    cp -r deps/minisat2-2.2.1 minisat-2.2.1
    patch -d minisat-2.2.1 -p1 < scripts/minisat-2.2.1-patch
    call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x64
    sed -i "s/BUILD_ENV[ ]*=.*/BUILD_ENV = MSVC/" src/config.inc
    make -C src -j2

test_script:
- cmd: |
    cd regression

    rem HACK disable failing tests
    rmdir /s /q ansi-c\arch_flags_mcpu_bad
    rmdir /s /q ansi-c\arch_flags_mcpu_good
    rmdir /s /q ansi-c\arch_flags_mthumb_bad
    rmdir /s /q ansi-c\arch_flags_mthumb_good
    rmdir /s /q ansi-c\Forward_Declaration2
    rmdir /s /q ansi-c\Incomplete_Type1
    rmdir /s /q ansi-c\Union_Padding1
    rmdir /s /q ansi-c\Universal_characters1
    rmdir /s /q ansi-c\function_return1
    rmdir /s /q ansi-c\gcc_attributes7
    rmdir /s /q ansi-c\struct6
    rmdir /s /q ansi-c\struct7
    rmdir /s /q cbmc\Malloc23
    rmdir /s /q cbmc\byte_update2
    rmdir /s /q cbmc\byte_update3
    rmdir /s /q cbmc\byte_update4
    rmdir /s /q cbmc\byte_update5
    rmdir /s /q cbmc\byte_update6
    rmdir /s /q cbmc\byte_update7
    rmdir /s /q cbmc\pipe1
    rmdir /s /q cbmc\unsigned___int128
    rmdir /s /q cbmc-cpp
    rmdir /s /q cpp\Decltype1
    rmdir /s /q cpp\Decltype2
    rmdir /s /q cpp\Function_Overloading1
    rmdir /s /q cpp\enum2
    rmdir /s /q cpp\enum7
    rmdir /s /q cpp\enum8
    rmdir /s /q cpp\nullptr1
    rmdir /s /q cpp\sizeof1
    rmdir /s /q cpp\static_assert1
    rmdir /s /q cbmc-java\VarLengthArrayTrace1
    rmdir /s /q cbmc-java\classpath1
    rmdir /s /q cbmc-java\jar-file3
    rmdir /s /q cbmc-java\tableswitch2
    rmdir /s /q goto-gcc
    rmdir /s /q goto-instrument\slice08

    make test

    cd ..
    make -C unit all
    make -C unit test
