[package]
name = "libcprover_rust"
version = "5.81.0"
edition = "2021"
description = "Rust API for CBMC and assorted CProver tools"
repository = "https://github.com/diffblue/cbmc"
documentation = "https://diffblue.github.io/cbmc/"
license = "BSD-4-Clause"
exclude = ["module_dependencies.txt", "Cargo.lock"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"

[lib]
crate-type = ["rlib"]
doctest = false
